version: 2
updates:
  - package-ecosystem: "cargo"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      rust-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    target-branch: "dev"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
