name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  dependency-review:
    permissions:
      contents: read
      pull-requests: write
    uses: Conxian/.github/.github/workflows/dependency-review.yml@ac8cec76cb2e2e222bac3f8703f4b0a16cb86db3 # main
